include: package:flutter_lints/flutter.yaml

analyzer:
  # errors:
  #   unused_import: warning
  #   unnecessary_getters_setters: warning
  #   unnecessary_null_comparison: warning
  #   unnecessary_this: warning
  #   prefer_single_quotes: warning
  #   prefer_const_constructors: warning
  #   prefer_final_fields: warning
  #   prefer_final_locals: warning
  #   prefer_is_empty: warning
  #   unnecessary_new: warning
  #   unnecessary_cast: warning
  #   missing_return: error
  #   dead_code: error
  #   type_annotate_public_apis: warning
exclude:
  - build/**
  - .dart_tool/**
  - lib/generated_plugin_registrant.dart


linter:
  rules:
 
    # - annotate_overrides
    # - avoid_print
    # - prefer_adjacent_string_concatenation
    # - prefer_collection_literals
    # - prefer_const_constructors_in_immutables
    # - prefer_initializing_formals
    # - avoid_returning_null_for_future
    # - prefer_const_literals_to_create_immutables
    # - prefer_final_locals
 
