name: app_gasto
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.18.1
  loading_animation_widget: ^1.2.1
  responsive_framework: ^0.2.0
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  dio: ^5.4.1
  flutter_modular: ^6.3.4
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  validatorless: ^1.2.3
  ionicons: ^0.2.2
  printing: ^5.12.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.0
  collection: ^1.18.0
  photo_view: ^0.15.0
  flutter_masked_text2: ^0.9.1
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^22.1.36
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/flags/
    - assets/util/
    - pubspec.yaml

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
